language: python
sudo: false
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - travis_retry pip install -r requirements-dev.txt
script:
  - nosetests
after_success:
  - nosetests --with-coverage --cover-erase --cover-html --cover-package=chaos_lambda
  - coveralls
