language: python
sudo: false
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - travis_retry pip install -r requirements-dev.txt
before_script:
  - pip install python-coveralls
  - pip install pytest-cov
script:
  - pytest
after_success:
  - coveralls
